
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[343] =
    {   0,
        0,    0,    0,    0,    0,    0,   59,   57,   42,   41,
       44,   43,   45,   36,   49,   46,   35,   57,   17,   18,
       33,   31,   39,   32,   57,   34,   50,   50,   38,   25,
       37,   26,   46,   46,   21,   57,   22,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   19,   57,   20,   56,   54,   56,   58,
       28,   49,   47,   49,   46,   46,   23,   40,   51,    0,
       53,   51,   51,    0,    0,   50,    0,   29,   27,   30,
       46,   46,   46,   52,   48,   46,   46,   46,   46,   46,
       46,   46,   46,   46,    4,   46,   46,   46,   46,   46,

       46,   46,   46,    7,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   24,   55,   49,   49,   49,   51,    0,
        0,   51,   51,   51,    0,    0,    0,   50,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   40,   46,
       46,   46,    8,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   49,   47,   49,   51,   51,   51,
        0,    0,    0,    0,   50,    0,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,    6,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,    2,   15,   46,   46,   49,   49,    0,    0,   51,
       51,   50,   46,   46,   46,   46,   46,   46,    3,   46,
       46,   46,   46,   40,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   40,   46,
       46,   16,   51,    0,   46,   14,   40,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   11,
       12,   13,   46,   46,   46,   46,    5,   40,    0,   46,

        1,   46,   46,   46,   46,   46,   46,   46,   46,   46,
        0,    0,   46,   46,   46,   46,   46,   46,    0,    0,
       46,   46,   46,    0,    0,   46,    0,    0,   46,    0,
        0,    0,    0,    0,    0,    0,    0,    9,    0,    0,
       10,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   22,   22,    1,   23,   24,
       25,   26,    1,    1,   27,   27,   27,   27,   28,   27,
       27,   27,   29,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   30,   27,   27,   27,   27,   27,   27,   27,
       31,   32,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    1,    1,    1,    1,    3,    3,    3,    3,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[349] =
    {   0,
        0,    0,   60,   61,    0,    0,  393, 1077, 1077, 1077,
     1077, 1077, 1077,  358,   57,   45, 1077,  356, 1077, 1077,
     1077,  341, 1077,  335,   47,  317,   62,   66, 1077,  303,
      290,  280,   50,   56, 1077,   94, 1077,   86,   70,   90,
       82,   95,  127,  129,  132,  134,  136,  142,   58,  144,
      163,  138,  146, 1077,  242, 1077, 1077, 1077,  262, 1077,
     1077,   78, 1077,  181,  160,    0, 1077, 1077,  196,  239,
     1077,  185,  187,  206,  189,  217,  220, 1077, 1077, 1077,
      222,  198,  170, 1077, 1077,  224,  231,  237,  234,  239,
      242,  244,  246,  248,  250,  259,  252,  263,  268,  274,

      276,  278,  280,  286,  288,  291,  297,  299,  302,  305,
      309,  313,  318,  315,  320,  326,  328,  338,  342,  344,
      349,  351,  353, 1077, 1077,  105,  368,  112,  364,  367,
      214,  370,  377,  396,  388,  404,  393,  412,  415,  407,
      417,  423,  420,  426,  439,  441,  431,  434,  445,  453,
      460,  462,  465,  467,  469,  471,  478,  480,  384,  488,
      490,  495,  499,  503,  497,  505,  507,  509,  512,  520,
      524,  528,  532,  534,  536,  538,  546,  540,  548,  550,
      560,  552,  565,  567,  561,  285,  576,  573,  581,  597,
      209,  589,  599,  585,  609,  613,  616,  618,  620,  623,

      627,  629,  631,  633,  639,  641,  643,  648,  650,  654,
      659,  661,  665,  667,  669,  674,  678,  682,  689,  691,
      693,  695,  700,  706,  709,  712,  714,  718,  720,  722,
      724,  726,  732,  735,  742,  718,  347,  739,  194,  746,
      762,  753,  758,  764,  770,  772,  774,  777,  781,  787,
      792,  789,  794,  797,  799,  803,  809,  812,  815,  818,
      820,  823,  826,  828,  840,  843,  845,  847,  849,  857,
      859,  853,  861,  195,  863,  867,  871,  873,  882,  884,
      886,  890,  894,  896,  899,  902,  904,  906,  910,  912,
      919,  925,  927,  929,  932,  934, 1077,  938,  184,  940,

      943,  947,  951,  953,  960,  955,  962,  966,  968,  974,
      181,  162,  979,  981,  983,  985,  988,  996,  177,  146,
      998, 1003, 1005,  143,  155, 1007,  117,  111, 1013,  107,
       89,  106,   90,   81,   76,   65,   62, 1077,   53,   47,
     1077, 1077, 1064, 1067, 1070,   79, 1073,   70
    } ;

static yyconst flex_int16_t yy_def[349] =
    {   0,
      342,    1,  343,  343,  344,  344,  342,  342,  342,  342,
      342,  342,  342,  342,  345,  346,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  346,  346,  342,  342,  342,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  342,  342,  342,  342,  342,  342,  342,
      342,  345,  342,  347,  346,  348,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      346,  346,  346,  342,  342,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  342,  342,  347,  345,  345,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  347,  347,  347,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  347,  347,  342,  342,  342,
      342,  342,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  342,  342,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  342,  346,  342,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      342,  342,  346,  346,  346,  346,  346,  346,  342,  342,
      346,  346,  346,  342,  342,  346,  342,  342,  346,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,    0,  342,  342,  342,  342,  342,  342
    } ;

static yyconst flex_int16_t yy_nxt[1140] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,    8,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   16,   16,   33,   34,
       35,   36,   37,   16,   38,   39,   40,   41,   42,   43,
       44,   16,   45,   16,   16,   46,   16,   47,   16,   48,
       49,   50,   51,   16,   52,   53,   16,   16,   16,   54,
       55,   56,   58,   58,   63,   66,   66,   69,   69,   72,
       66,   66,   66,   72,   59,   59,   66,   66,   66,   66,
       73,   65,   74,   74,   73,   63,   76,   76,   64,   72,
       66,   66,   70,   72,  341,   75,  114,   81,  340,   77,

       72,   84,   66,   66,   72,   85,   66,   66,   82,   64,
       66,   66,  342,   83,  339,   66,   66,  338,   88,   63,
       94,   86,   72,  337,   90,   84,   72,   89,  336,   85,
       95,   91,  335,   84,  334,   92,  185,   87,   93,  333,
       96,   84,   97,   64,   84,  332,   84,   66,   66,   66,
       66,   98,   66,   66,   66,   66,   66,   66,   66,   66,
      331,   99,   66,   66,   66,   66,   66,   66,  330,  100,
      108,  104,  101,  328,  109,  102,  111,  103,  105,  106,
       66,   66,  107,   66,   66,  115,  122,  123,   62,  110,
       66,   66,  112,  327,  129,  113,  116,  117,  325,  118,

      132,  119,  132,  129,  120,  133,  133,  134,  134,  136,
      136,  324,  127,  121,  129,  320,   69,   69,   66,   66,
      128,  141,   75,  129,   73,  129,   74,   74,  128,  130,
      319,  128,  312,  128,  129,   73,  297,   76,   76,  135,
      138,  138,   66,   66,   66,   66,  274,  129,  140,  239,
      137,   66,   66,   77,   66,   66,  129,   66,   66,   66,
       66,  191,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,  139,  142,  148,  131,  149,   66,
       66,  125,  143,   66,   66,  144,  145,  151,   66,   66,
      146,  147,  342,  150,   66,   66,   66,   66,   66,   66,

       66,   66,  124,  152,   80,  154,   66,   66,   66,   66,
      153,   66,   66,  156,   79,  155,  185,   66,   66,   66,
       66,  157,   66,   66,  158,   66,   66,   78,  159,   66,
       66,   71,  160,   66,   66,   66,   66,  161,   66,   66,
       66,   66,  162,  163,  164,  167,   66,   66,   66,   66,
      166,  165,   68,  170,  342,  168,   68,  159,   66,   66,
      173,  169,   66,   66,   66,   66,   67,  171,  172,   66,
       66,   66,   66,   66,   66,  186,  174,  175,  185,  188,
      176,  188,   61,  180,  189,  189,  178,  190,  190,  177,
      133,  133,  342,  182,  179,  184,  183,  133,  133,  187,

      130,  342,  181,  129,   66,   66,  159,  128,  194,  194,
      192,   72,  342,  195,  195,  128,  134,  134,  128,   72,
      128,  135,   73,  129,   74,   74,  137,   66,   66,  193,
       73,   72,   76,   76,  129,   66,   66,   66,   66,   72,
       66,   66,   72,   66,   66,  196,   66,   66,  342,  198,
       72,   66,   66,  197,   66,   66,  129,  342,  201,   66,
       66,   66,   66,  342,   72,   66,   66,  203,  342,  199,
      342,  202,   72,   66,   66,  200,  342,  159,  342,  159,
       66,   66,   66,   66,  159,   66,   66,   66,   66,   66,
       66,   66,   66,  342,  207,  342,  204,  208,   66,   66,

       66,   66,  342,  209,  205,  206,  342,  210,   66,   66,
       66,   66,  212,  159,  213,   66,   66,   66,   66,   66,
       66,  342,  211,   66,   66,   66,   66,   66,   66,   66,
       66,  342,   66,   66,  342,  214,  159,  217,  215,  218,
       66,   66,  342,  159,   66,   66,  342,  216,   66,   66,
      159,  219,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,  342,  220,  221,  222,   66,   66,   66,   66,
       66,   66,   66,   66,  227,  342,  226,  223,  224,  342,
       66,   66,  229,   62,  225,   66,   66,   66,   66,  233,
      228,  159,  236,  189,  189,  342,  230,  231,  232,  234,

      237,  189,  189,   73,  129,   74,   74,  127,  237,  240,
      240,  237,  235,  237,  238,  128,  342,   69,   69,  241,
      241,  342,  192,  128,  129,  342,  128,   73,  128,   76,
       76,  342,  193,  242,  242,  129,   66,   66,   66,   66,
       66,   66,  196,   66,   66,  342,  196,   66,   66,   66,
       66,   66,   66,   66,   66,  342,  243,  129,  245,   66,
       66,   66,   66,   66,   66,  244,  342,  248,   66,   66,
       66,   66,  159,  246,   66,   66,  342,  247,  342,   66,
       66,   66,   66,  250,  249,   66,   66,   66,   66,   66,
       66,  159,  342,  252,   66,   66,  251,  232,   66,   66,

      342,  253,   66,   66,  342,  255,  254,  342,  257,   66,
       66,   66,   66,   66,   66,   66,   66,  159,  342,  256,
       66,   66,  342,  260,  342,  261,   66,   66,  258,   66,
       66,  262,   66,   66,   66,   66,  259,  263,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,  266,  236,
      264,  265,   66,   66,  267,   66,   66,  237,  159,  273,
      273,  268,   66,   66,  159,  237,  133,  133,  237,  129,
      237,  342,  238,  242,  242,  270,  342,  269,   66,   66,
      272,  342,  134,  134,   66,   66,  196,  271,  342,  129,
       66,   66,   66,   66,   66,   66,  275,   66,   66,  342,

      129,   66,   66,  342,  276,  342,  278,   66,   66,   66,
       66,  279,   66,   66,   66,   66,  277,   66,   66,   66,
       66,  342,  129,   66,   66,  342,  159,  159,  342,   66,
       66,  282,   66,   66,  280,   66,   66,  281,   66,   66,
       66,   66,  283,   66,   66,  284,   66,   66,   66,   66,
      342,  286,  342,  159,  342,  159,  285,  342,  287,  289,
       66,   66,  290,   66,   66,   66,   66,   66,   66,   66,
       66,  342,  288,   66,   66,  291,  292,   66,   66,   66,
       66,  189,  189,   66,   66,  342,  159,   66,   66,  299,
      342,   66,   66,   66,   66,  293,  342,  294,  342,  295,

      159,  296,   66,   66,   66,   66,   66,   66,  342,  300,
       66,   66,  342,  298,   66,   66,   66,   66,  342,   66,
       66,  342,   66,   66,   66,   66,   66,   66,  342,  301,
       66,   66,   66,   66,  303,  304,  305,  302,  159,   66,
       66,  159,  159,  342,  159,   66,   66,   66,   66,   66,
       66,  159,   66,   66,   66,   66,  311,  342,   66,   66,
       66,   66,  306,   66,   66,  342,  307,   66,   66,  342,
      309,   66,   66,   66,   66,   66,   66,  308,  342,  310,
       66,   66,   66,   66,  342,  159,   66,   66,   66,   66,
      342,  314,  159,  316,   66,   66,  315,  342,  313,   66,

       66,   66,   66,   66,   66,   66,   66,  342,   66,   66,
      342,  159,  159,  317,  342,  318,   66,   66,   66,   66,
      342,  159,  159,   66,   66,   66,   66,   66,   66,  322,
      323,  321,  342,   66,   66,  342,  342,  342,  342,  342,
      342,  342,  159,  342,  342,  329,  342,  342,  159,  159,
      159,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  326,   57,   57,   57,   60,   60,   60,
       62,  342,   62,  126,  342,  126,    7,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342
    } ;

static yyconst flex_int16_t yy_chk[1140] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,   15,   16,   16,   25,   25,   27,
       33,   33,  348,   28,    3,    4,   34,   34,   49,   49,
       27,  346,   27,   27,   28,   62,   28,   28,   15,   27,
       39,   39,   25,   28,  340,   27,   49,   33,  339,   28,

       27,   36,   41,   41,   28,   36,   38,   38,   34,   62,
       40,   40,  126,   34,  337,   42,   42,  336,   39,  128,
       41,   38,   27,  335,   40,   36,   28,   39,  334,   36,
       41,   40,  333,   36,  332,   40,  126,   38,   40,  331,
       42,   36,   42,  128,   36,  330,   36,   43,   43,   44,
       44,   42,   45,   45,   46,   46,   47,   47,   52,   52,
      328,   43,   48,   48,   50,   50,   53,   53,  327,   43,
       47,   45,   43,  325,   47,   43,   48,   44,   45,   45,
       65,   65,   46,   51,   51,   50,   52,   53,   64,   47,
       83,   83,   48,  324,   73,   48,   50,   50,  320,   50,

       72,   50,   72,   69,   51,   72,   72,   73,   73,   75,
       75,  319,   64,   51,   73,  312,   69,   69,   82,   82,
       64,   83,   75,   69,   74,   73,   74,   74,   64,   69,
      311,   64,  299,   64,   69,   76,  274,   76,   76,   74,
       77,   77,   81,   81,   86,   86,  239,   73,   82,  191,
       76,   87,   87,   77,   89,   89,   69,   88,   88,   90,
       90,  131,   91,   91,   92,   92,   93,   93,   94,   94,
       95,   95,   97,   97,   81,   86,   91,   70,   92,   96,
       96,   59,   87,   98,   98,   88,   89,   94,   99,   99,
       90,   90,  186,   93,  100,  100,  101,  101,  102,  102,

      103,  103,   55,   95,   32,   97,  104,  104,  105,  105,
       96,  106,  106,   99,   31,   98,  186,  107,  107,  108,
      108,  100,  109,  109,  101,  110,  110,   30,  102,  111,
      111,   26,  103,  112,  112,  114,  114,  105,  113,  113,
      115,  115,  106,  106,  107,  111,  116,  116,  117,  117,
      110,  108,   24,  113,  237,  112,   22,  109,  118,  118,
      116,  112,  119,  119,  120,  120,   18,  114,  115,  121,
      121,  122,  122,  123,  123,  127,  116,  117,  237,  129,
      118,  129,   14,  121,  129,  129,  120,  130,  130,  119,
      132,  132,    7,  122,  120,  123,  122,  133,  133,  127,

      130,    0,  121,  134,  159,  159,  121,  127,  135,  135,
      133,  136,    0,  137,  137,  127,  134,  134,  127,  138,
      127,  135,  136,  134,  136,  136,  137,  140,  140,  134,
      138,  136,  138,  138,  134,  139,  139,  141,  141,  138,
      143,  143,  136,  142,  142,  138,  144,  144,    0,  140,
      138,  147,  147,  139,  148,  148,  134,    0,  143,  145,
      145,  146,  146,    0,  136,  149,  149,  147,    0,  141,
        0,  144,  138,  150,  150,  142,    0,  145,    0,  146,
      151,  151,  152,  152,  148,  153,  153,  154,  154,  155,
      155,  156,  156,    0,  151,    0,  149,  152,  157,  157,

      158,  158,    0,  153,  150,  150,    0,  155,  160,  160,
      161,  161,  157,  154,  158,  162,  162,  165,  165,  163,
      163,    0,  156,  164,  164,  166,  166,  167,  167,  168,
      168,    0,  169,  169,    0,  161,  160,  163,  161,  165,
      170,  170,    0,  164,  171,  171,    0,  162,  172,  172,
      166,  167,  173,  173,  174,  174,  175,  175,  176,  176,
      178,  178,    0,  168,  169,  170,  177,  177,  179,  179,
      180,  180,  182,  182,  175,    0,  174,  171,  172,    0,
      181,  181,  177,  187,  173,  183,  183,  184,  184,  182,
      176,  178,  185,  188,  188,    0,  179,  180,  181,  183,

      185,  189,  189,  194,  190,  194,  194,  187,  185,  192,
      192,  185,  184,  185,  189,  187,    0,  190,  190,  193,
      193,    0,  192,  187,  190,    0,  187,  195,  187,  195,
      195,    0,  193,  196,  196,  190,  197,  197,  198,  198,
      199,  199,  195,  200,  200,    0,  196,  201,  201,  202,
      202,  203,  203,  204,  204,    0,  197,  190,  199,  205,
      205,  206,  206,  207,  207,  198,    0,  202,  208,  208,
      209,  209,  203,  200,  210,  210,    0,  201,    0,  211,
      211,  212,  212,  206,  204,  213,  213,  214,  214,  215,
      215,  205,    0,  208,  216,  216,  207,  211,  217,  217,

        0,  210,  218,  218,    0,  214,  212,    0,  216,  219,
      219,  220,  220,  221,  221,  222,  222,  213,    0,  215,
      223,  223,    0,  219,    0,  220,  224,  224,  217,  225,
      225,  221,  226,  226,  227,  227,  218,  222,  228,  228,
      229,  229,  230,  230,  231,  231,  232,  232,  226,  236,
      223,  225,  233,  233,  228,  234,  234,  236,  224,  238,
      238,  229,  235,  235,  227,  236,  240,  240,  236,  241,
      236,    0,  238,  242,  242,  231,    0,  230,  243,  243,
      235,    0,  241,  241,  244,  244,  242,  234,    0,  241,
      245,  245,  246,  246,  247,  247,  243,  248,  248,    0,

      241,  249,  249,    0,  244,    0,  246,  250,  250,  252,
      252,  248,  251,  251,  253,  253,  245,  254,  254,  255,
      255,    0,  241,  256,  256,    0,  247,  252,    0,  257,
      257,  253,  258,  258,  250,  259,  259,  251,  260,  260,
      261,  261,  254,  262,  262,  255,  263,  263,  264,  264,
        0,  258,    0,  259,    0,  256,  257,    0,  260,  262,
      265,  265,  263,  266,  266,  267,  267,  268,  268,  269,
      269,    0,  261,  272,  272,  264,  265,  270,  270,  271,
      271,  273,  273,  275,  275,    0,  267,  276,  276,  277,
        0,  277,  277,  278,  278,  266,    0,  268,    0,  270,

      269,  271,  279,  279,  280,  280,  281,  281,    0,  278,
      282,  282,    0,  275,  283,  283,  284,  284,    0,  285,
      285,    0,  286,  286,  287,  287,  288,  288,    0,  279,
      289,  289,  290,  290,  284,  285,  286,  280,  281,  291,
      291,  282,  287,    0,  288,  292,  292,  293,  293,  294,
      294,  283,  295,  295,  296,  296,  298,    0,  298,  298,
      300,  300,  289,  301,  301,    0,  293,  302,  302,    0,
      295,  303,  303,  304,  304,  306,  306,  294,    0,  296,
      305,  305,  307,  307,    0,  302,  308,  308,  309,  309,
        0,  304,  300,  306,  310,  310,  305,    0,  303,  313,

      313,  314,  314,  315,  315,  316,  316,    0,  317,  317,
        0,  307,  310,  308,    0,  309,  318,  318,  321,  321,
        0,  315,  316,  322,  322,  323,  323,  326,  326,  314,
      317,  313,    0,  329,  329,    0,    0,    0,    0,    0,
        0,    0,  322,    0,    0,  326,    0,    0,  318,  321,
      329,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  323,  343,  343,  343,  344,  344,  344,
      345,    0,  345,  347,    0,  347,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[59] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jac.l"


#line 4 "jac.l"
	//podem faltar includes
	/*
		output=0 nao imprime
		output=1 imprime	
	*/
	int output = 0;
	int num_line = 0;
	int num_col = 0;
#line 854 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define ERROR 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 22 "jac.l"

#line 1045 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 343 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1077 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 23 "jac.l"
{if(output) printf("BOOL\n");}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "jac.l"
{if(output) printf("BOOLLIT\n");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "jac.l"
{if(output) printf("CLASS\n");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "jac.l"
{if(output) printf("DO\n");}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "jac.l"
{if(output) printf("DOTLENGTH\n");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "jac.l"
{if(output) printf("ELSE\n");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "jac.l"
{if(output) printf("IF\n");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "jac.l"
{if(output) printf("INT\n");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "jac.l"
{if(output) printf("PARSEINT\n");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "jac.l"
{if(output) printf("PRINT\n");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "jac.l"
{if(output) printf("PUBLIC\n");}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "jac.l"
{if(output) printf("RETURN\n");}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "jac.l"
{if(output) printf("STATIC\n");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 36 "jac.l"
{if(output) printf("STRING\n");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 37 "jac.l"
{if(output) printf("VOID\n");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 38 "jac.l"
{if(output) printf("WHILE\n");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 39 "jac.l"
{if(output) printf("OCURV\n");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 40 "jac.l"
{if(output) printf("CCURV\n");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 41 "jac.l"
{if(output) printf("OBRACE\n");}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 42 "jac.l"
{if(output) printf("CBRACE\n");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 43 "jac.l"
{if(output) printf("OSQUARE\n");}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 44 "jac.l"
{if(output) printf("CSQUARE\n");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 45 "jac.l"
{if(output) printf("AND\n");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 46 "jac.l"
{if(output) printf("OR\n");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 47 "jac.l"
{if(output) printf("LT\n");}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 48 "jac.l"
{if(output) printf("GT\n");}	
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 49 "jac.l"
{if(output) printf("EQ\n");}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 50 "jac.l"
{if(output) printf("NEQ\n");}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 51 "jac.l"
{if(output) printf("LEQ\n");}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 52 "jac.l"
{if(output) printf("GEQ\n");}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 53 "jac.l"
{if(output) printf("PLUS\n");}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 54 "jac.l"
{if(output) printf("MINUS\n");}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 55 "jac.l"
{if(output) printf("STAR\n");}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 56 "jac.l"
{if(output) printf("DIV\n");}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 57 "jac.l"
{if(output) printf("MOD\n");}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 58 "jac.l"
{if(output) printf("NOT\n");}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 59 "jac.l"
{if(output) printf("ASSIGN\n");}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 60 "jac.l"
{if(output) printf("SEMI\n");}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 61 "jac.l"
{if(output) printf("COMMA\n");}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 62 "jac.l"
{if(output) printf("RESERVED(%s)\n",yytext);}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 65 "jac.l"
{num_col=0;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 66 "jac.l"
{;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 67 "jac.l"
{;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 68 "jac.l"
{;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 69 "jac.l"
{;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 71 "jac.l"
{if(output)printf("ID(%s)\n",yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 72 "jac.l"
{if(output)printf("STRLIT(%s)\n",yytext);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 73 "jac.l"
{printf("Line <num linha>, col <num coluna>: invalid escape sequence (%s)\n",yytext);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 74 "jac.l"
{if(output)printf("Line <num linha>, col <num coluna>: unterminated string literal (%s) \n",yytext);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 75 "jac.l"
{if(output)printf("DECLIT(%s)\n",yytext);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 76 "jac.l"
{if(output)printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 77 "jac.l"
{;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 81 "jac.l"
{BEGIN COMMENT;}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 82 "jac.l"
{num_col = 0;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 83 "jac.l"
{BEGIN 0;printf("\n");}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "jac.l"
{;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 85 "jac.l"
{printf("Line <num_linha>, col <num_col>: unterminated comment");}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 87 "jac.l"
{printf("Line <num linha>, col: illegal character (%s)\n",yytext);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 88 "jac.l"
ECHO;
	YY_BREAK
#line 1434 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ERROR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 343 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 343 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 342);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 88 "jac.l"


int main(int argc, char* argv[])
{
	if(argc>1)
	{
		{/*caso a flag seja -l ou -1 nao deve imprimir os tokens*/}
		if(strcmp(argv[1],"-l") == 0 || strcmp(argv[1],"-1") == 0)
		{
			output = 1 ;
		}

	}
	yylex();
	return 0;
}

int yywrap()
{
	return 1;
}

